# Generated by Django 5.0.1 on 2026-02-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='emails_emai_prospec_89e89f_idx',
            old_name='emails_emaillog_prospect_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='emails_emai_status_e97e19_idx',
            old_name='emails_emaillog_status_idx',
        ),
        migrations.RenameIndex(
            model_name='emaillog',
            new_name='emails_emai_sent_at_bfffc0_idx',
            old_name='emails_emaillog_sent_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='emails_enro_prospec_736af6_idx',
            old_name='emails_enrollment_prospect_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='emails_enro_sequenc_3df7c3_idx',
            old_name='emails_enrollment_sequence_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='emails_enro_status_fc285d_idx',
            old_name='emails_enrollment_status_idx',
        ),
    ]
