# Generated by Django 5.0.1 on 2026-02-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='dashboardview',
            new_name='analytics_d_user_id_4b4e1d_idx',
            old_name='analytics_dashboardview_user_idx',
        ),
    ]
