# Generated by Django 5.0.1 on 2026-02-12 13:38

import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_client'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_created_721afe_idx',
            old_name='accounts_au_created_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_user_id_2e9d8e_idx',
            old_name='accounts_au_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='accounts_au_content_d34376_idx',
            old_name='accounts_au_content_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_email_74c8d6_idx',
            old_name='accounts_us_email_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_1fa9a5_idx',
            old_name='accounts_us_role_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
