# Generated by assistant: add status constants choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrichment', '0002_alter_importjob_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
