# Generated by Django 5.0.1 on 2026-02-12 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_add_score_breakdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='client',
            new_name='crm_client_country_22324b_idx',
            old_name='crm_client_country_idx',
        ),
        migrations.RenameIndex(
            model_name='client',
            new_name='crm_client_status_1220b0_idx',
            old_name='crm_client_status_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='crm_interac_prospec_b67a7a_idx',
            old_name='crm_interaction_prospect_idx',
        ),
        migrations.RenameIndex(
            model_name='interaction',
            new_name='crm_interac_date_82825f_idx',
            old_name='crm_interaction_date_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='crm_prospec_country_0eda89_idx',
            old_name='crm_prospect_country_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='crm_prospec_stage_1245c4_idx',
            old_name='crm_prospect_stage_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='crm_prospec_priorit_f832c1_idx',
            old_name='crm_prospect_priority_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='crm_prospec_owner_i_be2927_idx',
            old_name='crm_prospect_owner_id_idx',
        ),
        migrations.RenameIndex(
            model_name='prospect',
            new_name='crm_prospec_created_871a33_idx',
            old_name='crm_prospect_created_idx',
        ),
        migrations.AlterField(
            model_name='client',
            name='account_manager',
            field=models.ForeignKey(limit_choices_to={'role': 'commercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='contact_role',
            field=models.CharField(blank=True, help_text='e.g., Director, Manager, Principal', max_length=100, verbose_name='contact role'),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'commercial'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='score_last_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
